title: "都市更新公告專區"
url: "https://littled3092.github.io"
baseurl: "/urban-renewal-page"

theme: minima

# collections:
#   notices:
#     output: true
#     permalink: /notices/:path/

# defaults:
#   - scope: { path: "", type: notices }
#     values:
#       layout: page
#       lang: zh-TW

header_pages:
  - notices.md
  - about.md

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/LittleD3092" }
